### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by sergioradovcic** [api-ai/api-ai-cordova#1]
Building with Telerik fails with the following error

Link: ld: framework not found Metal for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sstepashka** [comment]
Which plugin id? (Telerik)

Need:
1) XCode version.
2) Cordova version.
3) List of installed plugins (cordova plugin ls)

**Comment by sstepashka** [comment]
We don't use Metal framework in library, matbe it solution for you problem? 
https://www.appsee.com/blog/dev/xcode-new-link-frameworks-automatically-fix-framework-not-found-metal-for-architecture-armv7
