### ISSUE TITLE
iOS 9 Xcode 7 build failing

### ISSUE THREAD

**Issue by jamesgrayillustration** [api-ai/api-ai-cordova#10]
Getting the following error:

    ld: warning: object file (/Users/james/Code/gray/platforms/ios/gray/Plugins/ai.api.apiaiplugin/libApiAI.a(AIDefaultConfiguration.o)) was built for newer iOS version (7.1) than being linked (7.0)
    ld: '/Users/james/Code/gray/platforms/ios/gray/Plugins/ai.api.apiaiplugin/libApiAI.a(AIDefaultConfiguration.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sstepashka** [comment]
Now you can set ENABLE_BITCODE to false.

**Comment by jamesgrayillustration** [comment]
@sstepashka Thanks, but is that really the best way to handle this?

**Comment by sstepashka** [comment]
@jamesgrayillustration, No, We will update library with this feature. In few days.

**Comment by jamesgrayillustration** [comment]
Thanks @sstepashka - any update?

**Comment by sstepashka** [comment]
@jamesgrayillustration Hi, I'm now update library. Please, try update library.

**Comment by jamesgrayillustration** [comment]
@sstepashka - thanks, I think it worked.

**Comment by jamesgrayillustration** [comment]
@sstepashka , well it works - but FYI I am getting a bunch of warnings now.
