### ISSUE TITLE
Speech Recognition Engine - No recognition result matched

### ISSUE THREAD

**Issue by kshitizshankar** [api-ai/api-ai-cordova#11]
Hi, I am trying to play around with cordova API.ai SDK but I am having issues in setting it up.
I have a very random behavior where I get "{\"message\":\"Speech recognition engine error: No recognition result matched.\"}" most of the times. 

I have attached my relevant code below as well. It is just a basic call to the API SDK.

    $scope.sendVoice = function(){
    try {
      ApiAIPlugin.requestVoice(
        {}, // empty for simple requests, some optional parameters can be here
        function (response) {
            // place your result processing here
			console.log(JSON.stringify(response);
        },
        function (error) {
            // place your error processing here
			console.log(JSON.stringify(error));

        });                
    } catch (e) {
        alert(e);
    }
    }

Here is the code for my button -
```html
    <button class="button" ng-click="sendVoice()">
```

I am getting the same error when I try to use the cordova sample as well. It was working fine on the day I installed the app on my Samsung S4 but it stopped working after a few hours and I have been getting the same error every since. I tried to debug the issue but haven't been able to figure it out so far. Every time the button is clicked, the error callback gets executed. 

If I click the button again immediately, it works for the next request.
(So yeah, not sure what is going on here).

**Comment by xVir** [comment]
Hi, @kshitizshankar !
We will publish the new version of SDK in few days, in new version problem should be solved.

**Comment by kshitizshankar** [comment]
@xVir Oh ok, so this is a SDK problem? I wasn't sure whether something was messed up at my end.
Any strict timeline on when the new SDK would be available?

**Comment by xVir** [comment]
@kshitizshankar it can be the SDK problem... If new SDK will not solve the problem I will make a test app to check your problem. New SDK we plan to release this week.

**Comment by kshitizshankar** [comment]
@xVir Sure, thanks!

**Comment by xVir** [comment]
Hi, @kshitizshankar ,
Please try to install this test app https://www.dropbox.com/s/w4zlsjhrqw7551c/android-debug.apk?dl=0
And check if the problem still exists. (Use `Voice Request` option)
Also, please attach the android log here.
Thanks!
