### ISSUE TITLE
Output recognized text before further processing

### ISSUE THREAD

**Issue by xVir** [api-ai/api-ai-cordova#12]
Add callback, which will be called after speech recognition and before call to the API.AI service to give developer option to display recognized text (or some another processing).

**Comment by xVir** [comment]
cc @kshitizshankar

**Comment by kshitizshankar** [comment]
@xVir Thanks for adding the issue! 
Let me know if I can help out with anything to bring this feature up and ready asap :)

**Comment by xVir** [comment]
Hi, @kshitizshankar 
Please update plugin to version 1.5.2
Now it contains method `setPartialResultsCallback`, so set callback like this
```js
ApiAIPlugin.setPartialResultsCallback(function (results) {
    console.log(results);
});
```
**results** - the string with json array of recognition results.
Please try the plugin and let me know if any problems appear.

Thanks!

**Comment by kshitizshankar** [comment]
@xVir Awesome! Will check it out today. Thanks! :)

**Comment by kshitizshankar** [comment]
@xVir I tried integrating the setPartialResultsCallback but it keeps sending the text it caches after every word (not sure how it works in the background). For example, if I say "How are you doing today" - the output I get in the callbacks are - "How", "How are", "How are you", "How are you doing", "How are you doing today". Is there a direct way to get only the last call?

**Comment by xVir** [comment]
@kshitizshankar, yes, it works as expected. Because of it is using the appropriate callback from Android Speech Recognizer. I can make another callback for the last recognition result.

**Comment by xVir** [comment]
Hi, @kshitizshankar 
Please update plugin to version 1.5.3 and try this
```js
ApiAIPlugin.setRecognitionResultsCallback(function (results) {
   console.log(results);
});
```
