### ISSUE TITLE
ApiAIPlugin.requestText

### ISSUE THREAD

**Issue by hsmith825** [api-ai/api-ai-cordova#13]
If I execute ApiAIPlugin.requestText, I get an unauthorized 401.  My code is as follows:

ApiAIPlugin.requestText(
            {
            query: encodeURIComponent(wtext),
            sessionId: "1234567890", // sessionId
            lang: "EN" // set lang tag from list of supported languages
            },
        function (response) {
            // place your result processing here
            alert(JSON.stringify(response));
            },
        function (error) {
            // place your error processing here
            alert("sendText, error = " +error);
            });

Any help is appreciated!
Howard

**Comment by hsmith825** [comment]
I am on IOS.

**Comment by sstepashka** [comment]
https://github.com/api-ai/api-ai-cordova#usage

Try following:

```javascript
ApiAIPlugin.init(
        {
            subscriptionKey: "YOUR_SUBSCRIPTION_KEY", // insert your subscription key here
            clientAccessToken: "YOUR_CLIENT_ACCESS_TOKEN", // insert your client access key here
            lang: "ru" // set lang tag from list of supported languages
        }, 
        function(result) { /* success processing */ },
        function(error) { /* error processing */ }
    );
```

**Comment by hsmith825** [comment]
Hi,

 

I was using the ApiAIPlugin.init as you show.  This works for other API.AI request.  Infact it is up and running on Android.  I decided to use the ApiAI https: request directly with no problem.

 

Thanks!

Howard

**Comment by hsmith825** [comment]
I decided to use the API directly on IOS as defined on the API ai site.  No problem.

Thanks!
