### ISSUE TITLE
weather.search - incomplete answer

### ISSUE THREAD

**Issue by r4nm4** [api-ai/api-ai-cordova#14]
Hi,
I'm starting to use this amazing plugin and I'm using "ApiAIPlugin.requestVoice" function.
When I try to search something with the "weather.search" like "Weather in London" from the AI.API I receive the complete and correct anwer, but this plugin "cut" part of the answer.
For example:
I'm asking: weather in London.
The Json answer from the API is:
{
  "id": "3c8a24da-85d2-451d-b6da-a723d0b91b53",
  "timestamp": "2016-01-21T05:43:20.979Z",
  "result": {
    "source": "domains",
    "resolvedQuery": "weather in london",
    "action": "weather.search",
    "parameters": {
      "request_type": "explicit",
      "location": "london"
    },
    "metadata": {
      "suggests": [
        {
          "title": "What about this weekend?",
          "weight": 50,
          "type": 0
        },
        {
          "title": "Send me weather notifications",
          "weight": 50,
          "type": 0
        },
        {
          "title": "Repeat",
          "weight": 50,
          "type": 0
        }
      ],
      "widget": {
        "name": "html",
        "heightAspect": "80%",
        "data": {
          "url": "https://s3.amazonaws.com/static.speaktoit.com/widgets/weather/index.html?{\"region\":\"London\",\"speedUnit\":\"mph\",\"selected\":0,\"today\":0,\"s\":\"F\",\"d\":\"F\",\"locale\":\"en-US\",\"data\":[{\"day\":\"01/21/2016\",\"t1\":\"42\",\"t2\":\"38\",\"t\":\"30\",\"c\":\"Intermittent Clouds\",\"i\":\"partly_sunny\",\"w\":\"8\",\"mobileLink\":\"http://m.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day\\u003d1\"},{\"day\":\"01/22/2016\",\"t1\":\"50\",\"t2\":\"40\",\"t\":\"50\",\"c\":\"Rain\",\"i\":\"rain\",\"w\":\"13\",\"mobileLink\":\"http://m.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day\\u003d2\"},{\"day\":\"01/23/2016\",\"t1\":\"51\",\"t2\":\"46\",\"t\":\"51\",\"c\":\"Intermittent Clouds\",\"i\":\"partly_sunny\",\"w\":\"6\",\"mobileLink\":\"http://m.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day\\u003d3\"},{\"day\":\"01/24/2016\",\"t1\":\"53\",\"t2\":\"48\",\"t\":\"53\",\"c\":\"Intermittent Clouds\",\"i\":\"partly_sunny\",\"w\":\"10\",\"mobileLink\":\"http://m.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day\\u003d4\"},{\"day\":\"01/25/2016\",\"t1\":\"54\",\"t2\":\"44\",\"t\":\"54\",\"c\":\"Mostly Cloudy\",\"i\":\"cloudy\",\"w\":\"11\",\"mobileLink\":\"http://m.accuweather.com/en/gb/london/ec4a-2/daily-weather-forecast/328328?day\\u003d5\"}]}"
        }
      },
      "api-fulfillment": true,
      "complainId": "ae30271f-ea21-4104-bca5-b70757220bd7",
      "speech": "It's currently 30 degrees and light fog in London. This afternoon you can expect cloudy, with temperatures around 32 degrees. This evening you can expect mostly sunny, with temperatures around 40 degrees.",
      "response.trigger.action": "weather.suggest",
      "action": "weather.search",
      "response.event.action": "weather.search",
      "html": "  Here's the weather forecast for London.  ",
      "parameters": {
        "request_type": "explicit",
        "location": "london"
      },
      "listen": "false",
      "account": {
        "type": "anonymous"
      }
    },
    "fulfillment": {
      "speech": "It's currently 30 degrees and light fog in London. This afternoon you can expect cloudy, with temperatures around 32 degrees. This evening you can expect mostly sunny, with temperatures around 40 degrees."
    }
  },
  "status": {
    "code": 200,
    "errorType": "success"
  }
}
What I really need to have is: "metadata.widget.data.url", but unfortunately the plugin truncate the "metadata" object. Or maybe is my mistake and I don't know how to read this information.

 If I'm trying to debug with chrome/inspect the result from the plugin is:
Object {id: "9d6e816e-898d-46e2-b115-f14dde187def", result: Object, status: Object, timestamp: "2016-01-21T05:46:23.906Z"}
id: "9d6e816e-898d-46e2-b115-f14dde187def"
result: Object
action: "weather.search"
fulfillment: Object
metadata: Object
__proto__: Object
__defineGetter__: __defineGetter__()
__defineSetter__: __defineSetter__()
__lookupGetter__: __lookupGetter__()
__lookupSetter__: __lookupSetter__()
constructor: Object()
hasOwnProperty: hasOwnProperty()
isPrototypeOf: isPrototypeOf()
propertyIsEnumerable: propertyIsEnumerable()
toLocaleString: toLocaleString()
toString: toString()
valueOf: valueOf()
get __proto__: get __proto__()
set __proto__: set __proto__()
parameters: Object
resolvedQuery: "weather in London"
__proto__: Object

As you can see "metadata" is a object but without anything inside.

Anyone can help me please?
Is it my mistake or is a bug?
Thank you so much for your help.

All the best

**Comment by xVir** [comment]
Hi! 
Sorry,
The `widget` part in metadata not supposed to get into production version. This is a temporary problem, and this metadata will be removed soon. 
Please describe what for would you like to use it? Maybe it can be solved in another way.

Thanks!

**Comment by r4nm4** [comment]
Hi @xVir 
first of all thank you so much for you answer :)
No problem at all, I can find another way ;)

At the moment, I'd like to have the "metadata.widget.data.url" from "weather.search".
Because with the url in answer I can display the weather widget inside an iframe ;)

Thanks

**Comment by xVir** [comment]
Weather domain gives parameter `"location": "london"`, so you can use it for getting weather information from some service, like http://apidev.accuweather.com/developers/ and create your own widget.

Thanks! :)
