### ISSUE TITLE
Speech recognition engine - insufficient permissions

### ISSUE THREAD

**Issue by citynorman** [api-ai/api-ai-cordova#16]
Hello api.ai team!

I've cloned the sample app repo, made no changes to code (seems sample keys are used) and ran "cordova run android" and get "speech recognition: insufficient permissions" error on the voice request page after init success.

Think it has something to do with Android 6. Using:
cordova 6.0.0
android 6.0.1 on Nexus 6P or Nexus 5 API 23 (emulator)

Would you happen to know how to deal with the issue?

**Comment by xVir** [comment]
Hi, @citynorman 
Work with permissions is changed in Android 6, so I will update the plugin in nearest time.

Thanks.

**Comment by xVir** [comment]
Hi, @citynorman 

I've updated the plugin to version 1.5.5.
Now it will check audio recording permissions in Android 6.0.

Thanks.

**Comment by citynorman** [comment]
Perfect, thanks for the swift update!
