### ISSUE TITLE
Could not find com.android.support:support-v4:23.2.1

### ISSUE THREAD

**Issue by r4nm4** [api-ai/api-ai-cordova#17]
Dear xVir,
I'm sorry to bother you, but this morning I have just updated your plugin from 1.4.2 to 1.6.0
and this issue came out. Could you please help me fixing that?
Now I'm trying to rollback on the old version, otherwise I'm in stuck.
Thank you.

Could not find com.android.support:support-v4:23.2.1.
Searched in the following locations:
https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.pom
https://repo1.maven.org/maven2/com/android/support/support-v4/23.2.1/support-v4-23.2.1.jar

**Comment by r4nm4** [comment]
I fixed this issue with:
android update sdk --no-ui --all --filter "extra-android-m2repository"
Thanks

**Comment by xVir** [comment]
Thanks! 
Yes, the problem is caused by Android SDK version.

You can also update it with Android SDK Manager

![screen 2016-03-22 11 06 52](https://cloud.githubusercontent.com/assets/278221/13942583/a5d16fac-f026-11e5-903d-b52441366130.png)

Thanks!
