### ISSUE TITLE
zh-TW language is not working

### ISSUE THREAD

**Issue by kn4rfy** [api-ai/api-ai-cordova#18]
I have tried `en`, `zh-CN`, `zh-HK`, `zh-TW` but `zh-TW` is not working
Here is the debug log:
`zhTW`

> 2016-06-14 16:46:27.481 NED[824:641216] zh-TW
> 2016-06-14 16:46:27.572 NED[824:641216] THREAD WARNING: ['ApiAIPlugin'] took '90.564209' ms. Plugin should use a background thread.
> 2016-06-14 16:46:27.659 NED[824:641216] Api.ai init success
> 2016-06-14 16:46:38.341 NED[824:641216] start-listening
> 2016-06-14 16:46:39.824 NED[824:641216] THREAD WARNING: ['ApiAIPlugin'] took '20.799805' ms. Plugin should use a background thread.
> 2016-06-14 16:46:39.886 NED[824:641216] stop-listening
> 2016-06-14 16:46:41.749 NED[824:641216] Error in Success callbackId: ApiAIPlugin1187424800 : TypeError: undefined is not an object (evaluating 'response.result.resolvedQuery')

The other languages works

**Comment by xVir** [comment]
Hi, @kn4rfy 
The problem appears on Android or iOS?

Thanks.

**Comment by kn4rfy** [comment]
It only appears on iOS

**Comment by kn4rfy** [comment]
I'm not a native Chinese speaker and I am only developing an app for a Chinese client and it seems the `zh-TW` only recognise "Ni Hao". Others can recognise other words.

**Comment by xVir** [comment]
Hi, @kn4rfy 
Sorry, our support of the `zh-TW` recognition is rather limited.
It would be better to use some third-party libs to recognize this type of Chinese language.

Thanks.

**Comment by kn4rfy** [comment]
Okay. Thanks. Maybe you could suggest something for me?

**Comment by xVir** [comment]
It seems it supported in [Nuance](https://developer.nuance.com/public/index.php?task=supportedLanguages), some support there is in [iSpeech](http://www.ispeech.org/api) and it should be supported in [Google Speech API](https://cloud.google.com/speech/)

**Comment by kn4rfy** [comment]
Thanks.
