### ISSUE TITLE
iOS Build Fail Telerik Appbuilder

### ISSUE THREAD

**Issue by ranieri82** [api-ai/api-ai-cordova#2]
Using the cordova plugin within Telerik App Builder's Windows IDE. Android deploys and works correctly, however iOS fails to build with the following error log:

[2015-02-17 09:34:33.531] Log (Info,None): Project "XXXX.tmp.proj" (default targets):
	iOS Build Tooling revision 2015.2.15.1

	Link: ld: framework not found Metal for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Done building project "XXXX.tmp.proj" -- FAILED.

[2015-02-17 09:39:13.762] Log (Info,None): Project "XXXX.tmp.proj" (default targets):
	iOS Build Tooling revision 2015.2.15.1

	Link: ld: framework not found Metal for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	Link: ld: framework not found Metal for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sstepashka** [comment]
We don't use Metal framework in library, matbe it solution for you problem? 
https://www.appsee.com/blog/dev/xcode-new-link-frameworks-automatically-fix-framework-not-found-metal-for-architecture-armv7

More information is needed:

1) XCode version.
2) Cordova version.
3) List of installed plugins (cordova plugin ls)
