### ISSUE TITLE
Integration issues of ApiAi cordova plugin with other Plugins requiring AV

### ISSUE THREAD

**Issue by srikanthNutigattu** [api-ai/api-ai-cordova#20]
We are trying to integrate API.ai cordova plugin with other code/plugins requiring AV access (eg: for Text-to-Speech). But the cordova plugin ie(ApiAIPlugin.m) I can see few issues happing with integration.
1. ApiAIPlugin.m - init has setCategory as AVAudioSessionCategoryPlayAndRecord, only AVAudioSessionCategoryRecord is sufficient as it is not exclusive mode?
2. init method has setActive:YES, can we initialize when it is needed? not on initialization? eg: inside requestVoice and set it back to NO on completion?

**Comment by sstepashka** [comment]
Hey @srikanthNutigattu, 
I'm currently resolving this issue. I'll notify when it will be done.

**Comment by sstepashka** [comment]
>  1. ApiAIPlugin.m - init has setCategory as AVAudioSessionCategoryPlayAndRecord, only AVAudioSessionCategoryRecord is sufficient as it is not exclusive mode?

How we cab play audio promt before recording?

> 2. init method has setActive:YES, can we initialize when it is needed? not on initialization? eg: inside requestVoice and set it back to NO on completion?

Really we should deactivate session? What if another plugin activate session before voice request?

**Comment by sstepashka** [comment]
I consider you wishes and commit all changes. Library was already updated
