### ISSUE TITLE
Speech recognition on ios is a lot worse than on android

### ISSUE THREAD

**Issue by corrrso** [api-ai/api-ai-cordova#24]
Hi, i made an hybrid app running on ios and android thanks to apache cordova.

On the android version of the app, the speech recognition works incredibly well, but on ios you have to shout like hell to make it understand even a simple word. Is there anything i can do? i didn't find information about this problem on your website or on google.

I tried the app on an iPhone 5c (ios 10) and on an ipad air (ios 8.4)

**Comment by sstepashka** [comment]
Hi @corrrso ,

Our company's main focus is NLU (natural language understanding) and dialog management. We provide a platform for creating conversational interfaces (called agents) for apps, bots, and devices. These interfaces are designed to receive text as input information.

Depending on your app, bot, or device platform, speech recognition might be available natively. For example, if you are building an Action on Google or an Android app, they support speech recognition natively.

For some other platforms, speech recognition can be integrated as an additional component. 

API.AI doesn't provide speech recognition services. You can consider using Google Speech API or other 3rd party solution for speech recognition and use API.AI for building a conversational interface.

Let me know if you have any questions.

Regards,
Dmitriy
