### ISSUE TITLE
Timeout with my access token but not the demo access token

### ISSUE THREAD

**Issue by djMax** [api-ai/api-ai-cordova#25]
Not sure if this is a cordova thing or just a back end thing, but when I use my access token in the cordova demo app, it times out. Is there any other magic other than just copying the client token from the web site?

**Comment by djMax** [comment]
Is this project still active? Seems like not.

**Comment by ivandroid** [comment]
Same here. Using my client token causes timeout error. However it works with the demo token. Please fix this problem.

**Comment by djMax** [comment]
I've tried contacting them on forums, here, twitter, you name it. I don't think they're managing the platform anymore. I assume Google will shut it down any day.

**Comment by sstepashka** [comment]
@djMax @ivandroid Yes, This is really bug, that we try to fix. But voice recognition does not supporting for all new users, only back-compatbile and will be removed in future version of SDK. 

Message from API:

API.AI speech recognition is going to be deprecated soon. Use Google Cloud Speech API or other solutions.

**Comment by djMax** [comment]
Does this affect all SDKs? I'm just trying to wrk on a project with some 6th graders, so web would be ok, but if none of the SDKs work then I guess wit.ai will be a better fit. Google Speech API doesn't really seem to do most of what api.ai does.

**Comment by sstepashka** [comment]
@djMax This is affect for REST, thus this affect all SDKs. You can use browser SpeechRecognition, for example.
