### ISSUE TITLE
iOS Recording Prompt

### ISSUE THREAD

**Issue by ranieri82** [api-ai/api-ai-cordova#3]
With Android, when you begin the audio capture process, by default, you hear the Google Now recording "beep". With iOS it is pure silence. Is there any way to invoke the Siri mic sound when invoking the listening from iOS?

**Comment by artemgoncharuk** [comment]
We cannot use the default Siri sound (Siri does not have APIs in iOS). I think, though, we can find an open source audio snippet to use as the mic prompt.

**Comment by viethoang88** [comment]
+1

**Comment by jamesgrayillustration** [comment]
+1

@viethoang88 The way I'm doing it, when the audio prompt finishes playing, it seems that the API.AI requestVoice function doesn't get processed - I think it might have something to do with the cordova media plugin not running in the background? Maybe I should wrap the 'play audio' function in a promise and call API.AI's requestVoice when done? However, I am using Ionic and ngCordova, so i'm not sure if it has something to do with the quirkiness of those libraries/frameworks.

**Comment by sstepashka** [comment]
implemented.
