### ISSUE TITLE
Can't find ApiAIPlugin

### ISSUE THREAD

**Issue by riccardovittoria** [api-ai/api-ai-cordova#7]
Hello,
When I try to invoke one of the functions I have an alert "ReferenceError: Can't find variable: ApiAIPlugin"

I have also build an application from scratch:
cordova create hello com.example.hello HelloWorld
cordova platform add ios
cordova plugin add ai.api.apiaiplugin

Then I added the init in the onDeviceReady function of the index.js, substituted my keys.
Last I just copied your function in the index.html and copied the simple div with the mic text.

No better than a clean start like that, but I always have the same error.

Could you help me with that?
Thank you very much

**Comment by sstepashka** [comment]
Hello,

Can you attach your "index.js" file?

I'm trying you flow... all work

**Comment by riccardovittoria** [comment]
Sure, here you are, thanks!

**Comment by sstepashka** [comment]
no attachments.

01/04/15 12:43, riccardovittoria пишет:
> Sure, here you are, thanks!
>
>
>
>

**Comment by riccardovittoria** [comment]
Github does not recognize it and does not allow files different from images...
Do you want to give me an email address?

Thank you,
Riccardo

**Comment by riccardovittoria** [comment]
Copied and pasted below:

var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
		
		ApiAIPlugin.init(
			{
				subscriptionKey: "4e11d202-f0e4-45fc-953d-a742de6b76f7 ", // insert your subscription key here
				clientAccessToken: "506de649c3c946bbad9744b2cec92b6c", // insert your client access key here
				lang: "en" // set lang tag from list of supported languages
			}, 
			function(result) {/* success processing */ },
			function(error) {/* error processing */ }
    	);
		
    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

app.initialize();

**Comment by sstepashka** [comment]
I'm paste you code to "index.js" and all work successfully! 

Maybe update cordova by following:
sudo npm update -g cordova

Code from my example: https://gist.github.com/sstepashka/d81d1be2b2ef8dd2ba7f

**Comment by riccardovittoria** [comment]
Thank you for your response! So it's a cordova problem...
I tried to update it but I still have the same error... Do you have any other idea?
(I tried to use other plugins, like Capture, and cordova works perfectly)

Thanks again for your help

**Comment by sstepashka** [comment]
Can you send error log when trying update cordova?

**Comment by sstepashka** [comment]
Maybe error in ruby version...

I'm using 

$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by riccardovittoria** [comment]
No the error is "ReferenceError: Can't find variable: ApiAIPlugin"
Cordova updates ok.
But other plugins work, just the ApiAI ones does not, that's why I wanted to know if you have another idea of what could be the problem.

**Comment by sstepashka** [comment]
Which error is now?
Is called successful callback?... or failure?

**Comment by riccardovittoria** [comment]
The error is always the same, it gives me an alert saying it cannot find the variable ApiAIPlugin..

**Comment by sstepashka** [comment]
Please, send all project to issue.

**Comment by riyer15** [comment]
@sstepashka @riccardovittoria did you ever find a resolution to this issue? I am having the same error and tried all the same methods mentioned here.

**Comment by rvittoria90** [comment]
No, but that was long time ago. Api.ai has developed a great platform in the last year. I'm sure that they will be able to help you, write to the intercom console in your platform, they are very responsive.
