### ISSUE TITLE
iOS Speech Recognition

### ISSUE THREAD

**Issue by viethoang88** [api-ai/api-ai-cordova#8]
Hi, I tried running on iOS, Android and Web. 

I would like to ask why on iOS the speech recognition is not that accurate as on API.AI web "Try it now" feature? 

I tried to say "plot profit by country" 

on iOS it recognised as "coffee for my country" or "hello to feed my country"
but same sentence is 100% correctly recognised on web.

**Comment by sstepashka** [comment]
Which browser your use? Chrome using google speech recognition, other browsers user our speech recognition.

**Comment by viethoang88** [comment]
Hello you can close this issue. I have tested in real device and is much better than using iOS simulator.

**Comment by viethoang88** [comment]
I tested on real device and is working great compared to iOS simulator.
